### ISSUE TITLE
Fabric - Git datastore - High git pull period by default

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#1303]
currently we do a git push/pull once per second on each node in the fabric, to make nodes be synced.

That use jgit under the hood, that creates 2 threads during this which is discarded. So when fabric is idle, it keeps creating new threads all the time. Ideally we should ask jgit to allow to configure a thread pool it can use, so it dont have to throw-away all these threads all the time.

IMHO we should set a higher default value, maybe 5 sec. That is okay for demoing as well, so if you change a profile, then child containers will react after 0-5 sec.

You can set this option using

```
fabric:profile-edit --pid io.fabric8.datastore/gitPullPeriod=5000
```

Any thoughts?

**Comment by emanuelebaldassarre** [comment]
I understand that each container in a fabric has its git and git instances are kept aligned. this means that at each change to a profile all the git datastores are aligned and while running a karaf script to change several profiles this generates a big overhead since all the containers need to be aligned at each operation. My ask is: is there a way to change the ZK /fabric/registry/clusters/git and keep only the rootcontainers aligned having all the child/ssh containers to refer to the root containers ? I imagine that with 100 profiles and 100 containers each change has a big overhead on the whole system, preventing large scalability. Let me know if I missed something. thanks.
