### ISSUE TITLE
Add persistence to the registry pod

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#3349]
Every time I restart fabric8 I loose any images I've pushed to the private registry.  It would be great to add persistence to avoid this.  

https://github.com/fabric8io/fabric8/blob/master/bin/registry.json#L24

After speaking with @paoloantinori on a different subject he mentioned data containers and after reading I'm not sure if that approach or mounted volumes are best suited.

Is there an opinion for one over the other in this situation?

**Comment by jimmidyson** [comment]
In a Kubernetes world, data containers will only mount the same volume as the main container because volumes are specified on the pod & mount points are specified in the container specs. So I would say go with a normal Kubernetes volume for this. If you want to persist data even across wiping out your whole kubernetes installation, then make sure you're using a `HostDir` rather than an `EmptyDir`.

More info on Kubernetes volumes at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md.

**Comment by rawlingsj** [comment]
Thats good feedback thanks @jimmidyson.  Ok so lets go for the normal kubernetes volume for this.
