### ISSUE TITLE
Where is New button?

### ISSUE THREAD

**Issue by nmcl** [fabric8io/fabric8#3370]
![screen shot 2015-01-17 at 16 50 18](https://cloud.githubusercontent.com/assets/580667/5789596/ccaddf6c-9e69-11e4-9eac-8ef99c023abf.png)
Fedora20, Firefox. README.md for camel-servlet example ...

"1. Select `quickstarts` --> `war` --> `camel-servet`
1. Click the `New` button in the top right corner"

There's no New button afaict. See attached screenshot.

**Comment by jstrachan** [comment]
BTW you're in the Container perspective; not Kubernetes/Fabric8 (hence the Connect / JMX / Logs / Threads / Tomcat tabs).

But if you click on the camel.servlet link on the right hand pane; or click the top link on the left hand pane for "Camel Servlet" it should take you to the page for camel servlet (rather than the page showing all the WAR QuickStarts you can choose between).

When you are on the single page for an app, the Run button appears. There's no Run button yet on the overview pages showing a number of apps.

Incidentally, its much easier to just click "Run..." now on the new Apps page; much less confusing than navigating around the Library wiki pages

**Comment by davsclaus** [comment]
I guess this was using hawtio 1.x. The 2.x has a different app view with a run button. And the readme files for some of the quickstarts are V1 based - they need to be updated for V2

**Comment by davsclaus** [comment]
We will overhaul all the documentation when fabric8 code settles down a bit.
