### ISSUE TITLE
No Library Tab in Console (MQ Documentation out of Sync)

### ISSUE THREAD

**Issue by davidatkins** [fabric8io/fabric8#3457]
The Fabric8 MQ Documentation suggests using the 'Library' tab to install the various MQ apps. I'm no longer seeing the Library tab after creating a fresh Openshift environment via Vagrant. I'm guessing this is because the install script is now using the new Hawtio Console ?(https://github.com/fabric8io/fabric8/commit/e84e5eec90490fe7b4b18f73f89be13803299e8f)

**Comment by jstrachan** [comment]
doh sorry; my bad - I should have that fixed real soon. I hoped to have a release cut last night that fixed that a little (there's an App Library REST service now to act as the wiki/repo to load/edit the app menu - kinda like your iTunes library). Should have it fixed real soon...

**Comment by davidatkins** [comment]
No problem ... it's forcing me to figure out how to do things via Maven Plugins/Command Line :)

**Comment by jstrachan** [comment]
BTW we've a nice Run... button on the 2.x hawtio UI from the Apps tab that shows all the apps that are available in the [App Library](http://fabric8.io/v2/appLibrary.html
) (a git based wiki) in a single screen; so its much easier to start stuff up. This now works in 2.0.29 - it took longer than I thought to get the release to actually work :) 

We've separated the App Library from the hawtio kubernetes UI so that its an [optional server side REST service](http://fabric8.io/v2/appLibrary.html
) you can choose to use if you wish; meaning the hawtio console for kubernetes is pure HTML/CSS/JS so its very easy to embed in, say, OpenShift or any docker container. Its also a really really small docker image now too ;)

So hopefully next time you recreate your fabric8 (after a about a minute) you'll have nice icons again and the Run... button. We should have the Library tab re-enabled in hawtio 2.x very soon too...

**Comment by davidatkins** [comment]
To confirm, after an update i've got the run button, and app icons have also returned

**Comment by davsclaus** [comment]
Is there anyone still to do, or can we close this?

**Comment by davidatkins** [comment]
Hello, the actual Library tab still isn't available, although alternative ways to install apps are. James mentioned in IRC today that is should be back but after a fresh install i'm still not seeing it

**Comment by davsclaus** [comment]
Yeah we know that we need to go over all the quickstart / app docs and adjust them to the world of v2. We will get to them when things settle more down in fabric8 itself.
