### ISSUE TITLE
create a CDI way to inject the endpoint URLs for a particular service id into Java code

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3736]
for cases where we want to use custom load balancers and whatnot.

I guess really we'd need to use events so that the Java code can be notified when an endpoint is added/removed; so that the java code can react and build its own data structure to store the events.

The other option is we allow injection of a 'live' copy-on-write list thats iteration safe?

```
public class Cheese {
  @Inject
  public Cheese(@Protocol("http") @Endpoints("my-service") List<String> endpointUrls) { .... 
  }
}
```

Note that I think @jimmidyson just added a helper method to lookup endpoints using DNS lookups as well to avoid the REST API...

**Comment by iocanel** [comment]
Added a PR that does the following:

Adds a new qualifier @Endpoint that can be used on top of the existing @ServiceName and @Protocol annotations so that it can be used to inject Lists or Sets of endpoints. For example:

@Protococl("http")
@Endpoint
@ServiceName("super-cool-service")
List<String> services

If we want we can integrate @Endpoint with @Factories so that provided a @Factory that is capable of String -> MyType we can inject things like:

@Protococl("http")
@Endpoint
@ServiceName("super-cool-service")
List<MyType> services

**Comment by iocanel** [comment]
btw the pr doesn't include @jimmidyson  helper. I'll add that one in the next draft.

**Comment by iocanel** [comment]
The @Endpoint qualifier has been implemented and is expected to work both inside and outside Kubernetes. I think we can close it now.
