### ISSUE TITLE
the generic jenkins job DSL should query the gogs repos to iterate through them all and create CI builds for them

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4054]
right now the default job DSL can iterate through github organisations...
https://github.com/fabric8io/default-jenkins-dsl/blob/master/seedBuilds.groovy#L28-28

am hoping we can just configure the `gh` object with the URL of the gogs REST API (and probably the user/pwd from env vars) and iterate through repos in gogs.

**Comment by christian-posta** [comment]
So the gogs REST API is _very_ thin.. https://github.com/gogits/gogs/tree/master/routers/api/v1 and the awesome GitHub Java API from kohsuke (https://github.com/kohsuke/github-api) does not work with gogs. 

Alternatively we can try using this https://github.com/jstrachan/fabric8/blob/cdelivery/components/gitrepo-api/ReadMe.md

**Comment by jstrachan** [comment]
shame kohsuke-san's client doesn't work with gogs. Looks like this could be the API BTW: https://github.com/fabric8io/gogs/blob/openshift/cmd/web.go#L228-228

at least it should be able to browse repos.

But yeah, we can use our own client for now; as that definitely works for creating and browsing repos

**Comment by jstrachan** [comment]
extra bonus points to whoever does this too #4063 so we can register a gogs webhook for each repo we create a jenkins build for

**Comment by christian-posta** [comment]
yah @jstrachan the API for /user/repos is there, but the github api does GET /user first and then on that object does a list of the repos... and Gogs doesn't implement the GET /user resource :( But our own client works great. Will post code soon.

**Comment by christian-posta** [comment]
okay so i started using the gitrepo-api (https://github.com/fabric8io/fabric8/tree/master/components/gitrepo-api) and standalone it works great. but when I try using it from jenkins i get this crazy class loader clash: http://pastebin.com/XX25qTzh 
I've even forced it to use a newer version of Spring (https://github.com/christian-posta/default-jenkins-dsl/blob/ceposta-hack/preBuild.gradle#L15), but not sure how the wrong class loader gets in the way

Otherwise, I have a sample jenkins pipeline modeled after the one I used for the fuse/osev2 demo (https://github.com/christian-posta/ceposta-devops-ose)... It works great locally and generates what looks to be valid jenkins config.xml, but for the error above, I haven't been able to verify it yet in jenkins. Here's the code for the seed jenkins job dsl:

https://github.com/christian-posta/default-jenkins-dsl/blob/ceposta-hack/seedBuilds.groovy

**Comment by jstrachan** [comment]
yay, this is looking like its almost done now - yay! :)

**Comment by jstrachan** [comment]
this works with 2.1.10 now - yay!
http://fabric8.io/guide/cdelivery.html#installation
