### ISSUE TITLE
gogs service not available when loading up fabric8-forge app

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#4232]
So there is a race condition between apps that require services at startup (i.e., KubernetesClient doing CDI or Spring DI and injecting services at runtime) and when the service is available. 

Example, with the fabric8-forge app, it depends on the gogs service and uses CDI to get it:

https://github.com/christian-posta/fabric8/blob/master/forge/fabric8-forge-core/src/main/java/io/fabric8/forge/rest/main/GitUserHelper.java#L44-44

However, if that service is not available, then the fabric8-forge-web app won't boot up properly (end up with this in the container logs:

2015-06-17 19:36:16.125:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@1631d614{/,file:/tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-2830036390816670906.dir/webapp/,STARTING}{/maven/ROOT.war}
java.lang.RuntimeException: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:|Exception 0 :|java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default|?at io.fabric8.kubernetes.api.KubernetesClient.getServiceURL(KubernetesClient.java:1393)|?at io.fabric8.cdi.Services.toServiceUrl(Services.java:39)|? ....

also note the stack trace is all smushed together when it's appended (maybe how Weld does its outputs)...

If you blow away the pod and let kube recreate it, that works around the issue.

 Maybe implementing a grace period (or something?) in the CDI/spring DI logic to deal with these types of races? ... though that complicates things a bit :)

**Comment by jstrachan** [comment]
So we try and combine dependencies into an [app-group](https://github.com/fabric8io/quickstarts/tree/master/app-groups) so that related things are installed together; and each combined json file for an app group as the services first to avoid this issue. e.g. if you [install the cdelivery app](http://fabric8.io/guide/cdelivery.html#installation); the services are all first. 

There's no 'dependency' metadata yet in kubernetes; so there's no way to say "you cant' start pod X until service Y is created' unfortunately.

Generally the fabric8 maven tooling always puts the services first in the json to try help. Doing a recursive 'mvn fabric8:apply" in the `quickstarts/apps` won't work though. But you can use a service-only mode then non-service mode in [fabric8:apply](http://fabric8.io/guide/mavenFabric8Apply.html) to do things in 2 passes. e.g. via `-Dfabric8.apply.servicesOnly=true` or `-Dfabric8.apply.ignoreServices=true`

**Comment by jimmidyson** [comment]
Do we still order stuff correctly? I noticed the treeset stuff isn't used
any more. Wondering if we've lost the ordering?

**Comment by jstrachan** [comment]
I think this is now fixed. We had a regression where the sorting of services in JSON was not properly sorts first
