### ISSUE TITLE
create an apiman page describing the APIMan app and how it runs apiman console + gateway etc

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4310]

**Comment by donovanmuller** [comment]
Using the [Vagrant image](http://fabric8.io/guide/getStarted/vagrant.html) I'm trying to run apiman app from the [API registry](http://fabric8.io/guide/apiRegistry.html) section of the docs.

Clicked Run and everything pulled and started up.
Clicking the route `apiman.vagrant.f8` however, bring you to a Jetty 404 Not found page. I tried looking for a context root without success.
The apiman and proxy (not sure how the proxy fits in but guess that's what the issue is for :)) pods are running and started successfully (from checking logs) and the route has been configured in the openshift-haproxy pod.
How do I access the apiman UI?

Also, the doc seems to be out of date with the current release?
It mentions clicking Library (I do not have that tab) and the API Registry app (I only see apiman under K8 > Apps > Run list of apps. Am I missing something?

**Comment by KurtStam** [comment]
Hi @donovanmuller, you will need to restart your fabric8 console pod(s) to pick up the apiman endpoint info. As soon as you do that, an apiman tab appears in the hawtio fabric8 console. The apiman app exposes a REST API only. 

This requirement to restart the console will be gone in a few hours (on master anyway) - I'm working on making it so that the apiman plugin is aware of the currently namespace and it will be dynamic from then on. I will update the docs too right after. You are doing it all right :), the docs are just a bit out of date.

Cheers,

--Kurt

**Comment by donovanmuller** [comment]
@KurtStam I restarted the pod and it was restarted successfully but no joy. I only have K8, Projects and Logs tabs (default namespace).
I even reloaded the Vagrant image, same result.

I'll wait until tomorrow then... :)

**Comment by KurtStam** [comment]
Added documentation on our website: http://fabric8.io/guide/apiManagement.html
