### ISSUE TITLE
Upgrade apiman to 1.1.3.Final

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/fabric8#4628]
Would you be able to look at this please @KurtStam or @EricWittmann? Not just a simple update version number from 1.1.3.CR1 to 1.1.3.Final sadly... anything else is beyond me ;)

**Comment by EricWittmann** [comment]
What is the context here?  Just needing to upgrade apiman in f8?

If so, why upgrade apiman to 1.1.3.Final?  The latest community release is 1.1.5.Final, and I'm releasing 1.1.6.Final today.

In any case upgrading to a newer apiman means leveraging the new apiman microservices.  But even that may be premature given our recent decision (I think?) to use EAP as the basis for the apiman stuff (instead of jetty, which is what the apiman microservices use now because I followed the existing fabric8 quickstarts when I built them).  So I'm not sure if it makes sense to use the latest apiman stuff if we're just going to have to change it again later.

**Comment by jimmidyson** [comment]
@EricWittmann Yeah to upgrade the fabric8 gateway that uses apiman. I have no knowledge of that at all - something that @KurtStam worked on. The reason for 1.1.3.Final is nothing but, again, my ignorance.

Would be happy to take guidance on it from you experts of course :grin:

**Comment by davsclaus** [comment]
@KurtStam have you not upgraded aipman ?

**Comment by EricWittmann** [comment]
I think this issue is likely deprecated.  :)  We're currently using 1.2.0.Alpha3 of apiman for productization purposes.  We'll probably end up with 1.2.0.Final.

**Comment by KurtStam** [comment]
Yes we already went to 1.1.3.Final and moved to infinity and beyond. Closing this.
