### ISSUE TITLE
hawt-app-maven-plugin v2.2.54 - run.sh does not have execute permission  

### ISSUE THREAD

**Issue by fmm1wxc** [fabric8io/fabric8#5122]
We’re using the QuickStarts samples and it is using the hawt-app-maven-plugin for creating a Docker image.

We found that when it builds a /deployment/bin/run.sh  in the image, the run.sh does not have execution rights.  

We’re using version 2.2.54, building in a Windows 7 environment and deploying to a Virtualbox container running Centos.  

As a work around we run a container and login as root, modify the permissions and then commit the image, however this a bit clumsy.

**Comment by davsclaus** [comment]
@rhuss I wonder if this is something that needs looked into the base images or ?

**Comment by rhuss** [comment]
It could be an issue of the hawt-app plugin since it's the plugin which creates this script.

But when running on Windows, there might be permission problems in general. To workaround this you should set the assembly **mode** to **tar** in the [configuration](http://ro14nd.de/docker-maven-plugin/docker-build.html#build-assembly).

Does this help ?

**Comment by fmm1wxc** [comment]
Yes, added
				  <mode>tar</mode>
and that had the right permissions.

I suppose the quickstarts should be updated for the unfortunate souls who use Windows, but I also see the warning "The archive formats have the advantage that file permission can be preserved better (since the copying is independent from the underlying files systems), but might triggers internal bugs from the Maven assembler (as it has been in #171)"  
So not sure the proper course of action.
