### ISSUE TITLE
Camel forge - add endpoint should only show current components

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5557]
So you can only select among components that are on the classpath.

To add a new use add component command first.
This is to reduce the list to have 200+ components when you use this command.

**Comment by jstrachan** [comment]
the current Camel perspective of the webconsole now has a Components tab that lets you pick from the available components in a project:

<img width="1348" alt="camel-components" src="https://cloud.githubusercontent.com/assets/30140/12141434/2264dcda-b467-11e5-8d65-a2c759a01038.png">

if you select one and click Add Endpoint it then takes you to the add endpoint UI using that selection:
<img width="1214" alt="camel-add-endpoint" src="https://cloud.githubusercontent.com/assets/30140/12141458/4dbfde8e-b467-11e5-81fe-f42abdae1152.png">

it would be kinda nice in this case to hide the filter & name ;) - will see if I can do that. 

The missing bit though is if we select Add Endpoint on the Endpoints tab, it prompts you with the list of components to choose from - right now its showing all of them. I'll fix that so that though!

**Comment by jstrachan** [comment]
BTW polished the second page now; so that it auto-defaults an instance name (which is easy to change in the form or source code anyways) and moves the endpoint type to the bottom - so impatient users can just click Next straight away:

<img width="1355" alt="camel-add-endpoint" src="https://cloud.githubusercontent.com/assets/30140/12142591/32cc5e68-b471-11e5-9fcf-7caa49c806e1.png">
