### ISSUE TITLE
NodeJS workflow : when running a 2nd time the build, I get an issue of RC already exist

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5644]
I need to clean the deployed app in the staging & prod domains, to success in updating the application.

**Comment by jmlambert78** [comment]
Hee is the jenkins trace to elaborate the bug.
Entering stage Rolling upgrade Staging
Proceeding
[Workflow] kubernetesApply
[Workflow] } //withKubernetesPod
[Workflow] Run build steps as a Kubernetes Pod : End
[Workflow] } //node
[Workflow] Allocate node : End
[Workflow] End of Workflow
ERROR: Error during kubernetes apply: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/node-backbone-mongo2-staging/replicationcontrollers. Message: replicationControllers "node-backbone-mongo2-ee551aab9af81fbe84c87857141483bd" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], kind=replicationControllers, name=node-backbone-mongo2-ee551aab9af81fbe84c87857141483bd, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=replicationControllers "node-backbone-mongo2-ee551aab9af81fbe84c87857141483bd" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
Finished: FAILURE

**Comment by rawlingsj** [comment]
Yeah this is a bug, it's because its using the same version https://github.com/fabric8io/jenkins-workflow-library/blob/master/workflows/node/CanaryReleaseStageAndApprovePromote/Jenkinsfile#L9

With java we used a maven plugin to figure this out.  We should have a fix soon that will work out the next version after looking at the git tags.  For now as a workaround you can manually trigger the build in jenkins and override the version number then manually increment it.
