### ISSUE TITLE
web console - Overview page is messed up after recent change

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5682]
Notice how the arrows no longer align correctly in the recent change of the web console UI. Such as the nav bar to the left hand side (love the new nav bar btw).

![screen shot 2016-02-01 at 1 43 24 pm](https://cloud.githubusercontent.com/assets/477100/12717709/e8768e1e-c8e9-11e5-96c8-3736d08bcb3e.png)

**Comment by davsclaus** [comment]
@gashcrumb I wonder if you have seen this too ?

**Comment by davsclaus** [comment]
Using the vanilla vagrant image in our fabric8-install project

**Comment by theobolo** [comment]
Same problem here. 

Version : 2.2.107

**Comment by gashcrumb** [comment]
@davsclaus yeah, haven't had a chance to look into that yet.

**Comment by gashcrumb** [comment]
@davsclaus k, hoped there was a fix in jsplumb 1.7.6, turns out that's the latest we can use without having to switch our code to using the DOM api from jquery.  However, didn't seem to solve the issue, we call a jsplumb function to recalculate offsets when redrawing, but no luck.  I've cheated for the moment though and have hidden the sub-tabs on that page which helps a bit, but this view will likely need more work to get it working properly :-/

**Comment by gashcrumb** [comment]
BTW, the diagram page doesn't show this behavior anymore.
