### ISSUE TITLE
Placement of the Slave buildpod of Jenkins, needs a placement rule (on a multinode cluster)

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5689]
In my story https://github.com/fabric8io/fabric8/issues/5675 I explained the difficulties to use the fabric8 for a node/python/go.. type of language, as the workflow creates a new pod (slave) to make the job.
If this pod is not deployed on the same host as the jenkins, then there is an issue of access to files
see the related story above for logs.

**Comment by jimmidyson** [comment]
@iocanel Any thoughts on this?

**Comment by jmlambert78** [comment]
In an earlier discussion last week, it was said that the affinity was not supported in openshift/K8S yet
From the [](https://docs.openshift.org/latest/admin_guide/scheduler.html) doc, it seems that some affinity is supported so the jnlp buildpod should use this when started from the f8 workflow it seems.
JMarc

**Comment by iocanel** [comment]
To be honest I don't quite understand how we could apply the above in order to place build pods in the same node with the jenkins slave.

I can only see it working using a node selector. So it goes like this:

1. we can find out the "current" pod, via HOSTNAME or Jenkins slave name.
2. Through the pod status, we can obtain the hostIp.
3. Using the hostIp we can find the matching Node.
4. We can pass the Node labels as a node selector when creating the build pod.

**Comment by jmlambert78** [comment]
it seems to work now
