### ISSUE TITLE
fabric8-maven-plugin - Generates wrong description

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5920]
I deployed the kubernetes-zipkin using the mvn f8 plugin and after the pods et all are running, then in the run app the descriptions for all of those apps are using some sonartype description
https://github.com/fabric8io/kubernetes-zipkin

![screen shot 2016-04-11 at 10 47 06 am](https://cloud.githubusercontent.com/assets/477100/14421616/ec3192fe-ffd2-11e5-8294-8e4695745f46.png)

**Comment by rhuss** [comment]
@davsclaus @iocanel The reason is that this description by default is extracted from the POM's `<description>`. If the project doesn't define it itself, then it inherits the description from the parent pom, which in all our apps is

```xml
<parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>9</version>
    </parent>
```

which has exactly this default description.

Possible solutions which is not related to this plugin:

* Create a `src/main/fabric8/Summary.md` (and potentially also a `ReadMe.md`)
* Add a proper `<description>` to your `pom.xml`

These files are picked up in this order and added as documentation annotations.

**Comment by rhuss** [comment]
Closing this here since its more an issue for the users of the plugin.
