### ISSUE TITLE
Cannot find apps templates to install on GKE

### ISSUE THREAD

**Issue by grandmore** [fabric8io/fabric8#6105]
I have created a Kubernetes cluster on GKE using the [Docs](http://fabric8.io/guide/getStarted/gke.html) however there is a part missing. It says:

`"We will also install another pod that includes a base set of template apps that we can run later. So now run.."`

However there is no mention of this later on or where to get it. I have searched around but to no avail.

Can you let me know how to install this piece.

Thanks.
Stuart

**Comment by jstrachan** [comment]
Apologies; thats a bit of stale docs. Rather than having to install a microservice to provide a REST API to let folks get / put application templates; we switched over to using `ConfigMaps` on Kubernetes.  Though running on GKE using just the console-kubernetes.json doesn't create the ConfigMaps.

If you install fabric8 via the `gofabric8` tool it should setup your cluster just right though.
e.g. if you follow these instructions
http://fabric8.io/guide/getStarted/kubernetes.html

(basically to run `gofabric8 deploy -y`) it should populate the apps so that the `Run...` UI appears with loads of stuff you can play with on kubernetes

**Comment by grandmore** [comment]
Thanks for the info. I will try again.

**Comment by grandmore** [comment]
Installation worked this time however I am still getting the same crash error that I reported [fabric-forge does not start and crashes with "Error when validating..."](https://github.com/fabric8io/fabric8/issues/6110)

Any ideas?

Thanks.

**Comment by jstrachan** [comment]
@grandmore phew at least thats one issue down ;). I'm still pretty puzzled by the other error - looks like the rt.jar is corrupted. Just investigating and trying to reproduce here. Its kinda strange though!

**Comment by grandmore** [comment]
Looking forwards to a fix so I can use fabric8, I've been working through this all weekend.

**Comment by jstrachan** [comment]
@grandmore sorry to hear that - I hope we can figure this out ASAP!

**Comment by jstrachan** [comment]
BTW we've updated the GKE docs with a video of how to get started. http://fabric8.io/guide/getStarted/gke.html
