### ISSUE TITLE
Failed to create Deployment: Deployment.extensions "jenkins" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policycd-pipeline...................................................................✘ Deployment.extensions "jenkins" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6394]
Failed to create Deployment: Deployment.extensions "jenkins" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policycd-pipeline...................................................................✘ Deployment.extensions "jenkins" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy

**Comment by rawlingsj** [comment]
Can you check you have the right roles setup? http://fabric8.io/guide/getStarted/openshift.html#add-roles

Were there any other errors in the output following the `gofabric8 deploy`?

**Comment by chbe8475** [comment]
I also had this issue when running kubernetes, not openshift, on ubuntu 14.04. I had to do some changes in the kubernetes configuration to make it work. Since I was following [this](http://kubernetes.io/docs/getting-started-guides/ubuntu/) guide to install kubernetes, the fix may only apply to this limited case.
What I did was to change two occurences of `--allow-privileged=${5}` to `--allow-privileged=true` in the `kubernetes/cluster/ubuntu/util.sh` file and then did a reinstall of kubernetes.

**Comment by RobinsChens** [comment]
Thanks a lot,I have solved the problem

**Comment by RobinsChens** [comment]
@chbe8475 Thanks a lot,I have solved the problem

**Comment by RobinsChens** [comment]
@rawlingsj  Thanks a lot,I have solved the problem,but I have met new proplem with docker push https error
