### ISSUE TITLE
so slowly to create app from fabric-console 

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6490]
It took much time to  create app for me on the fabric-console,can you tell me why,please

**Comment by jstrachan** [comment]
we're not yet using a persistent volume cache for fabric8-forge; so the first time you use the console to create a Java based app it does take a while for fabric8-forge's JBoss Forge tools to download the maven dependencies for the projects; they are cached locally after the first time - so the second time it should be much faster.

I'm hoping we can figure out some better approach so that fabric8-forge pre-caches more of its local maven repo to avoid the initial startup time issues: https://github.com/fabric8io/fabric8-forge/issues/654

**Comment by RobinsChens** [comment]
@jstrachan  fine,best wish for you guys
