### ISSUE TITLE
chown: changing ownership of '/var/lib/mysql/': Operation not permitted

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6573]
chown: changing ownership of '/var/lib/mysql/': Operation not permitted

**Comment by jimmidyson** [comment]
A bit more information would be great! In general, the more info you can provide will help us to figure out what the problem is.

What are you trying to do? What steps did you follow to get this error? What versions of components involved are you using? Are there any further logs? That kind of stuff is pretty essential for us to help you. Thanks!

**Comment by RobinsChens** [comment]
i want to deploy mysql:5.7  into openshift with nfs,but it got the problem above

**Comment by rhuss** [comment]
The problem is that most images which are available on Docker Hub are not directly usable for OpenShift. The reason is, that OpenShift runs your container with an *arbitrary uid* (for security reasons). So the image much work according to this restriction and must not assume that it runs as root. 

The mysql image apparently assumes exactly this, i.e. that it is allowed to create directories and modify permission below `/var/lib/`. 

It's a limitation / restriction of OpenShift, not fabric8.

**Comment by RobinsChens** [comment]
@rhuss  thanks for your reply ,but the logging template that fabric8 provider  doesn't work as well .it logs 
chown: changing ownership of ‘/usr/share/elasticsearch/data’: Operation not permitted

**Comment by RobinsChens** [comment]
just use the management template is ok
